logging:
  level:
    root: info
    
loadtarget:
  host: http://localhost:8080
  
server:
  port: 8083
  
  
management:
  endpoints:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    web:
      exposure:
        include: "*"      
      
logging:
  level:
    org.springframework.cloud.gateway: error
    org.springframework.http.server.reactive: error
    org.springframework.web.reactive: error
    reactor.ipc.netty: error
