logging:
  level:
    root: info
#    org.springframework.cloud.gateway: TRACE
    
    
loadtarget:
  host: http://localhost:8080
  
server:
  port: 8083
  
  
endpoints:
  prometheus:
    enabled: true
  metrics:
    enabled: true
  