logging:
  level:
    root: info
    
loadtarget:
  host: http://localhost:8080
  
server:
  port: 8083
  
  
management:
  endpoints:
    prometheus:
      enabled: true
    metrics:
      enabled: true