logging:
  level:
    root: info
    
loadtarget:
  host: http://localhost:8080
  
server:
  port: 8083
  
  
management:
  endpoints:
    web:
      exposure:
        include: "*"   
  metrics:
    distribution:
      percentiles-histogram[http.server.requests]: true 
      sla:
        http:
          server:
            requests: 1ms, 5ms              
      
logging:
  level:
    org.springframework.cloud.gateway: error
    org.springframework.http.server.reactive: error
    org.springframework.web.reactive: error
    reactor.ipc.netty: error


